{{- range $preset := .Values.presets }}
{{- if $preset.enabled }}
---
apiVersion: core.openeverest.io/v1alpha1
kind: InstancePreset
metadata:
  name: {{ $.Values.provider.shortName }}-{{ $preset.name }}
  labels:
    {{- include "provider-valkey.labels" $ | nindent 4 }}
    app.kubernetes.io/component: preset
spec:
  {{- toYaml $preset.spec | nindent 2 }}
{{- end }}
{{- end }}
